title: [Business Performance Dashboard]
#logo: /img/headshot_circle.jpg
#description: [Luis Perez - Senior Data Analyst]
description: [link](https://lperzcal.github.io/)
#show_downloads: true
theme: jekyll-theme-slate
